### ISSUE TITLE
Lag on ListenerOnJoinEvent

### ISSUE THREAD

**Issue by AllyncID** [sekwah41/Advanced-Portals#441] opened 2024-08-29 13:17 UTC
![image](https://github.com/user-attachments/assets/e3af6842-c47d-4fad-bc52-b6a57ad38b34)

How to fix this issue?

**Comment by sekwah41** [comment] 2024-08-29 15:31
Ive seen gateway join event lag but never specifically this one. Typically, this shouldn't be that inefficient. What fork of Spigot are you using?

**Comment by AllyncID** [comment] 2024-08-29 15:39
UniverseSpigot

**Comment by sekwah41** [comment] 2024-08-29 15:46
What version of mc are you using, also would you mind testing a different performance fork to see if this is consistent? I've never heard of UniverseSpigot.

The issue here is most of the wait time seems to be from async task handlers so I don't believe the lag is from my plugin rather than deceptively may be looking like its coming from my plugin due to the async wait times.

Though I haven't tried to debug timings in a while and may be wrong.

Nothing in the code surrounding those checks should be inefficient to my knowledge and it should only be doing a single check for the block type. I suspect this may be something wed want feedback from the maintainers of UniverseSpigot.

**Comment by sekwah41** [comment] 2024-08-29 15:48
https://github.com/sekwah41/Advanced-Portals/blob/6a228d8e7d17d35b71a5223a25b65dfae2ce0f07/src/main/java/com/sekwah/advancedportals/bukkit/listeners/Listeners.java#L95-L118

Here is the code in question. 

Actually, how many portals do you have? I may be best to make the loop more efficient by checking the material only once.

**Comment by sekwah41** [comment] 2024-08-29 16:03
[Advanced-Portals-1.0.0.jar.zip](https://github.com/user-attachments/files/16801919/Advanced-Portals-1.0.0.jar.zip)

Please give this a test; if it's still having the same performance issue, then you will need to talk to UniverseSpigot. This check shouldn't be that inefficient anyway, even if it's repeated like 30 times or so.

**Comment by AllyncID** [comment] 2024-08-29 16:33
Okkk... thank you sir, lemme try

**Comment by sekwah41** [comment] 2024-08-29 17:03
Sorry if its a bit spammy, you caught me in a heavy dev mood with all my code editors open xD and I couldn't not experiment a little 😆

**Comment by sekwah41** [comment] 2024-08-30 23:09
Any news on this?

**Comment by AllyncID** [comment] 2024-09-04 07:42
![image](https://github.com/user-attachments/assets/27e95001-9259-44a5-9869-7c7d0179515d)
same

**Comment by AllyncID** [comment] 2024-09-04 07:43
https://spark.lucko.me/T203W843EJ

**Comment by sekwah41** [comment] 2024-09-04 07:47
I'll try to take a look at the timings tonight though i don't think I'll have time to make any changes.

Could you try another fork to see if your setup has the same issue on things like paper?

I'm curious about what UniverseSpigot has to say about these logs as most of the % seems to be in the mc code on asynchronous waiting.

**Comment by sekwah41** [comment] 2024-09-04 07:51
Actually I can't seem to find much info about universe spigot at all online. Could you link me to some of their website or something.

**Comment by AllyncID** [comment] 2024-09-04 07:57
https://discord.gg/5c2mKKTG they're only on discord

**Comment by sekwah41** [comment] 2024-09-04 10:57
Closing this issue as the timings are entirely pointing towards the concurrency code, causing this latency issue.

Tbh given the fact that the tps isn't having an issue at all its likely a false positive where its freezing using the concurrency locks so the function itself may be taking a while, but its allowing other parts of the tick to process.

![image](https://github.com/user-attachments/assets/a634a6dd-e2f6-4578-bd0b-e061e7602fe3)

Seeing as the entirety of the waiting time is attributed to Unsafe.park, this is why I believe it's a false positive.

The other evidence that this is pointing towards a false positive is the fact that Advanced Portals shows to be taking about 40-50% of the tick however the average MSPT is actually lower than the previous ticks in the logs you sent me.

If you are able to show this issue happening on another fork like Paper or Pufferfish I will look into it more though there is too much evidence pointing towards a false positive.

**Closed by sekwah41** 2024-09-04 10:57 UTC

**Comment by sekwah41** [comment] 2024-09-04 11:06
I would suggest opening a ticket and getting them to weigh in. Though unless there is a clear issue I can fix with my code this will be either a false positive. Or an issue on their end.

**Comment by MachineBreaker** [comment] 2024-09-14 11:24
UniverseSpigot developer here, this is not caused by us and this can happen on every fork including Paper, this happens because the chunk was unloaded at that time so getting the block type caused it to be loaded synchronously

**Comment by sekwah41** [comment] 2024-09-14 21:19
@MachineBreaker thanks for the info :D so yea it’s a false positive due to it freezing for a chunk load. Which seeing as the player is joining will likely have to be done for that chunk anyway.

Though if it causes a noticeable increase I guess I could look into hooking into other events for when the chunk is finally loaded.

Feel free to correct me if I'm wrong but it seems like a non issue for both my plugin and any forks of paper atm.

**Comment by MachineBreaker** [comment] 2024-09-14 22:02
> @MachineBreaker thanks for the info :D so yea I assume it’s a false positive due to it freezing for a chunk load. Which seeing as the player is joining will likely have to be done for that chunk anyway.
> 
> Though if it causes a noticeable increase I guess I could look into hooking into other events for when the chunk is finally loaded.
> 
> Feel free to correct me if I'm wrong but it seems like a non issue for both my plugin and any forks of paper atm.

You can probably try delaying your checks for like 1 tick to potentially allow the server load the nearby chunks? Unsure if that could work

**Comment by sekwah41** [comment] 2024-09-23 21:16
Actually, I am going to re-open this as it would be good to avoid the server loading the chunks synchronously. I believe they are loaded async. This would be a larger issue on some servers if loaded from a slower hard drive.

**Comment by sekwah41** [comment] 2024-12-11 04:46
Need to look into this now the recode is complete
