### ISSUE TITLE
Plugin causing lag and mspt spikes.

### ISSUE THREAD

**Issue by matipoirierg** [sekwah41/Advanced-Portals#446] opened 2024-10-11 01:37 UTC
https://spark.lucko.me/hZPXWAhqob

**Comment by TreemanKing** [comment] 2024-10-11 03:41
Duplicate of #439

**Comment by sekwah41** [comment] 2024-10-11 18:31
Same place different issue. This one is due to incredible inefficient reading of the file entities by spigot.

Paper and its forks have a Boolean you can pass in to avoid this spike but I haven't implemented any paper specific performance improvements yet.

**Comment by sekwah41** [comment] 2024-12-11 05:01
This even has been removed

**Closed** 2024-12-11 05:01 UTC
