### ISSUE TITLE
No Author Specified 

### ISSUE THREAD

**Issue by RareMaker50** [sekwah41/Advanced-Portals#326] opened 2022-04-17 01:22 UTC
I use an auto-update plugin, and for it to work it needs an author specified. It keeps putting out an error because on velocity because of "No Author Found". I have attached a screenshot below showing what it looks like. I hope you could just put an author there so it would work, I'd appreciate it.

![image](https://user-images.githubusercontent.com/58754060/163696181-f396df08-1d69-4c36-8c80-4aa06833542d.png)

**Comment by RareMaker50** [comment] 2022-04-25 07:43
Oh no, it's not required by velocity it just botches some plugins, Thank you!

**Comment by sekwah41** [comment] 2022-04-26 00:20
I'll add it as part of the recode or if I do a release sooner. Atm in just settling into a new job I started today so I'm a little busy.

**Comment by RareMaker50** [comment] 2022-04-26 00:31
Oh I understand, Thanks for making keeping this plugin free

**Comment by isaaclepes** [comment] 2022-09-29 23:02
My ticket is a duplicate of this ( #334)

**Comment by sekwah41** [comment] 2022-10-09 16:02
Hey, ill take a look at this once I have some parts set up. Should be able to make the tweak this week, i just had forgotten about it as its been quite hectic this year :)

As long as you reference an issue number itll automatically mention that it was mentioned in another ticket btw.

**Comment by isaaclepes** [comment] 2022-10-09 16:04
Awesome, thank you!

**Closed** 2022-10-24 11:11 UTC
Labels: bug
