### ISSUE TITLE
Nether and End portals do not allow players to use them

### ISSUE THREAD

**Issue by Ghazalan** [sekwah41/Advanced-Portals#329] opened 2022-05-20 07:59 UTC
Found an issue, no idea how or why. But i noticed removing AdvancedPortals fixes it.

Situation:

Player attempts to enter a normal Nether or End portal.
According to the server (If i use /tp playername) Their in the dimension they should go through as they pass the portal.
According to the playermodel, they never actually get transported to the other dimension, they just stay at the starting portal. No matter where this portal is located (Overworld, Nether, End) 

This leaves players unable to use any portals not created by the plugin until the next server reboot.

I have yet to find out what is causing it. Some players can still use regular portals as normal, others cant. It is not always the same players either, it happens completely random.

I'm figuring something is hijacking the portalevent, just cant find out what.

Console remains normal, no errors or exceptions.

**Comment by sekwah41** [comment] 2022-05-20 08:03
Portals only disable those events if you are near or inside a portal. Could you send me your portals.yml file?

**Comment by Ghazalan** [comment] 2022-05-20 08:13
https://bin.bloom.host/zurejateda.yaml
portals.yml from SMP backend.

Only backend i've noticed the bug on. as its the only backend that has "regular" portals.
Hub, minigame etc all uses AdvancedPortals to warp between worlds on the same backend. SMP only backend that only has 1 AdvancedPortal used to return to the hub backend.

**Comment by sekwah41** [comment] 2022-07-19 16:04
Would you mind possibly joining the discord and allowing me to join the server to take a look a the behavior vs what you are seeing.

Ill be able to outline it as a scenario to test against.

**Comment by MagmaBlock** [comment] 2022-09-02 12:15
This problem also happend on my server
It occurs after a plugin update. Some of my players said they can't using nether portal randomly, at first I think it's a permission problem, but using `/lp verbose` found nothing. After trying many times, I found that version 0.7.1 works well, versions later may have this problem

**Comment by sekwah41** [comment] 2023-06-03 00:08
If someone is able to provide a version of spigot, paper or anything that I can re-create this in I can take a look. Sorry for the major delay, I thought this was a smaller issue than it was as it seems to be very rarely reported.

**Comment by MightyGoldenOctopus** [comment] 2023-06-03 06:12
@sekwah41 I have the issue with Paper 1.19.4 Build 545 using the latest release (9.3) of the plugin

**Comment by sekwah41** [comment] 2023-06-03 15:23
I am away on business for the next few days though I will see what I can do/check. I will be back next week though so will definitely have time then.

**Comment by MightyGoldenOctopus** [comment] 2023-06-22 12:31
@sekwah41 Any new on that topic ?

**Comment by sekwah41** [comment] 2023-06-22 16:42
I am personally not able to re-create this. I've tried a bunch.

Does it work if you disable my plugin? I remember in the past, someone thought it was an issue with the plugin, but they hadn't properly linked the worlds via multiverse.

**Comment by MightyGoldenOctopus** [comment] 2023-07-20 13:32
Was finally fixed by using multiverse-netherportal

**Comment by MagmaBlock** [comment] 2023-07-20 14:29
> Was finally fixed by using multiverse-netherportal

???

**Comment by sekwah41** [comment] 2023-07-22 10:32
Weve been finding a number of users miss-blaming this plugin due to the vague message from advanced portals as well as myworld when they actually haven't linked the portals between worlds properly.

The original issue is the proper one that I believe I've added a fix for worst case issues in the next update.

**Comment by MightyGoldenOctopus** [comment] 2023-07-23 16:40
@sekwah41 No I mean the error was reproductible and real, this is an established fact that AdvancedPortals breaks vanilla nether portal at proximity, however this issue was solved accidentally when we had to setup Multuverse and nether portals were handled by Multiverse abstraction instead.

**Comment by sekwah41** [comment] 2023-07-24 01:01
@MightyGoldenOctopus if someone can give me the steps to reproduce this (ones I've been given so far I've been unable to) or is at least able to show me this on a server, then I would be able to work with them to be able to fix this.

The next update should hopefully fix a worst-case scenario which is what might be triggering this based on what people describe.

**Comment by RillSoji** [comment] 2023-10-09 00:32
@sekwah41 When a player dies on a different server from their bedspawn it breaks nether portals. When I started troubleshooting the issue I thought it was HuskHomes or HuskSync at first but eventually just started removing plugins til I found the one causing it and AdvancedPortals was it. 

Reproduce: 
1. Login to Server A, set down a bed, and set spawn. 
2. Teleport to Server B and die. 
3. Respawn on Server A and attempt to enter a nether portal. You will not be teleported. 

The only fix/workaround I've been able to figure out is that we have Advanced portals going out to the world borders where there are nether portals. If a person goes out to the world border and uses that nether portal then travels back to spawn and enters the portal back to the overworld... then nether portals will work for them again. No idea why that works to fix it but it does.

**Comment by RillSoji** [comment] 2023-10-10 16:24
I can get you logged in to the server where it's happening as well. Just poke me. <3

**Comment by RillSoji** [comment] 2023-11-05 05:33
After stripping down the server to it's bare bones with only the following installed with version numbers:
- velocity-3.2.0-SNAPSHOT-265
- paper-1.20.1-194
- Advanced-Portals-2.1.0
- 1 Proxy, 2 Backend Paper servers

While testing with my main account I had to die a few times to get the bug to reproduce. Then I whitelisted my cam account to test on a non-OP player and got it to bug out immediately without death. This is with the default config file, no changes have been made to AdvancedPortals.

Login to Server A, Create a nether portal and go through and back. Transfer to Server B, Create a nether portal and go through and back. This is to verify that the vanilla nether portals are working. 

On Server B create an AP destination. Go back to Server A and create an AdvancedPortal to Server B's destination. Create an AP destination on Server A. Go back to Server B and create an AdvancedPortal to Server A's destination.

Death Steps, OP/First Player
Start on Server A then use AP to travel to server B. Die. Return to Server A and attempt to use a nether portal and it will not work. 

Non-Death, Non-OP/Second Player Steps
Start on Server A, go through the nether portal and back to the overworld. This should work as expected. Take the AP to Server B and go through the nether portal and back to the overworld. This should also work as expected. Take the AP back to Server A. Attempt to go through the nether portal. It will not work. 

In other posts here you mentioned people are not linking their portals correctly. In my logs you can see me create the portals. If I'm not doing this correctly could you please let me know the correct order of commands to create and link portals to destinations. I do not have and am unwilling to install multiverse or other world control plugins in this environment. 

Logs:
https://gist.github.com/RillSoji/ceb5b8a8fe00a3a08208df727e40751a

**Closed** 2024-07-24 23:00 UTC
Labels: bug
