### ISSUE TITLE
Error in the cmd

### ISSUE THREAD

**Issue by KrohmKoala** [sekwah41/Advanced-Portals#18] opened 2015-11-08 15:00 UTC
When i launch my server in the latest version of spigot i got so many error, i let you see in the screenshot. 
![error](https://cloud.githubusercontent.com/assets/15716207/11020954/5b8db644-8631-11e5-94ab-4dd85c1b6157.PNG)

**Comment by sekwah41** [comment] 2015-11-08 19:54
The problem should be fixed now, please try this quick build I made. http://puu.sh/lei1B/fd9bb01f02.jar

The problem was only occouring if you had no portals.

**Comment by KrohmKoala** [comment] 2015-11-09 11:36
I've the same problem, it seems to create no problem (maybe my portal whose don't want to have a destination set with the commands) Do you want a french translate for your plugin ?

**Comment by sekwah41** [comment] 2015-11-09 11:41
Im confused, does the problem still occour or not? Also I will have to add support to create some sort of language file first. If support for languages that would be great :)

**Comment by sekwah41** [comment] 2015-11-09 11:41
Im confused, does the problem still occour or not? Also I will have to add support to create some sort of language file first. If support for languages that would be great :)

**Comment by sekwah41** [comment] 2015-11-09 11:43
Im confused, does the problem still occour or not? Also I will have to add support to create some sort of language file first. If support for languages that would be great :)

**Comment by KrohmKoala** [comment] 2015-11-09 11:44
It's smaller but i have this:
![capture](https://cloud.githubusercontent.com/assets/15716207/11032909/7cc0fb7e-86df-11e5-88fa-3b2bc9ca026d.PNG)

Just tell me when you had the support, i will translate during my wasting time :D

**Comment by sekwah41** [comment] 2015-11-09 11:57
There seems to be an odd bug with the interact event, does this error only show up when you have nothing in your hand by any chance? I want to verify what the problem is as I can't test anything till later today.

**Comment by sekwah41** [comment] 2015-11-09 12:01
Also I have reopened the issue even though it is a different error, I want to make sure this gets fixed and I dont forget about it :)

**Comment by KrohmKoala** [comment] 2015-11-09 12:03
it's when i place some blocks in my portal, trigger block or others

**Comment by sekwah41** [comment] 2015-11-09 12:09
I will do some tests tonight to try and get these errors, Could you also try another version of spigot just to check?

**Comment by KrohmKoala** [comment] 2015-11-09 12:10
I haven't sorry, i replace at every rebuild

**Comment by sekwah41** [comment] 2015-11-09 12:15
Its just a problem of one of the variables being null, I dont think it will effect the functioning of the code but it does make a mess of the console. I just need to find what line is causing the null errors then I can sort it out. Its just that the crash log isnt outputting very helpful data in this case :(

**Comment by KrohmKoala** [comment] 2015-11-09 13:49
No problems :)

**Comment by KrohmKoala** [comment] 2015-11-09 14:14
another problem, the first times i created portals, it works fine, but after some portals, i set destination, the game tells me that i have a destination but it's not set...
Is a problem of my serv (problem after reload ?) or it's me ? :D

**Comment by sekwah41** [comment] 2015-11-09 15:25
umm, im not sure. Sometimes code does change and can act odd. Ill check as the files may be resetting themselves because of some stupid code I have done xD Tbh I havent recoded the config accessors since I started coding. Do they say there is no destination instantly or after a reload?

**Comment by sekwah41** [comment] 2015-11-09 15:25
This is largest number of problems I have ever seen 1 person have xD

**Comment by KrohmKoala** [comment] 2015-11-09 15:33
I think it's a good thing ^^ it's for the stability of the plugin :p It came instantly even after the restart of the server, it set the portal but not the destination

**Comment by KrohmKoala** [comment] 2015-11-09 15:37
and does the "/portal portal" command is functionnal ? 'cause it don't give me portal block x)

**Comment by sekwah41** [comment] 2015-11-09 16:12
In older versions yes, but you cant get the portal as an item in 1.8 :( Also make sure you create a destination first.

**Comment by KrohmKoala** [comment] 2015-11-09 16:23
my destination is created, i see in the game the destination is set, your plugin tell us if the destination isn't created

**Comment by sekwah41** [comment] 2015-11-09 16:48
spelt correct? there may be something wrong with the destination config. Try warping to it with /warp or /destination warp

**Comment by KrohmKoala** [comment] 2015-11-09 16:50
if i add the destintion directly in my portals.yml it works

**Comment by KrohmKoala** [comment] 2015-11-09 19:03
when i shoot with my bow :
![capture2](https://cloud.githubusercontent.com/assets/15716207/11043404/dd5111a8-871c-11e5-92bc-8a7bf25e4f80.PNG)

**Comment by sekwah41** [comment] 2015-11-10 18:19
You arnt annoying ^.^ Im trying to make mods and plugins for people to enjoy so any problems I can fix which arn't the fault of the user I will be more than happy to fix when I have the time :)

**Comment by KrohmKoala** [comment] 2015-11-11 20:00
I'll try to find some bugs and crashes after the next update :D

**Comment by sekwah41** [comment] 2015-11-11 22:09
That would be great :) Thanks for the help, Its hard to find all the bugs alone and you are doing a great job at finding a lot xD

**Comment by KrohmKoala** [comment] 2015-11-13 11:01
I'm just looking at my cmd when i'm in my server ^^

**Comment by sekwah41** [comment] 2015-11-15 11:15
I dont know what build of spigot you are using or what is happening but I cant seem to get these errors at the moment .-.

**Comment by KrohmKoala** [comment] 2015-11-15 12:30
i'll rebuild spigot to get the new build (my actual build is from the 4 november ^^) and i will also test without all my other plugins to see if i get some error

**Comment by KrohmKoala** [comment] 2015-11-16 09:12
I've test without al my plygins, just leave yours but I still get the error, there's my build https://www.dropbox.com/s/cca8wuxd2hxvoqq/spigot.jar?dl=0

**Comment by sekwah41** [comment] 2015-11-19 10:36
Thanks, I will run some tests tonight :)

**Comment by KrohmKoala** [comment] 2015-11-19 10:53
no problem :) I'm glad to help you :)

**Comment by KrohmKoala** [comment] 2015-11-28 20:07
Have you some problems with my build ? :)

**Comment by sekwah41** [comment] 2015-11-29 17:37
Sorry I didnt get round to testing it, I have been busy with coursework T^T

**Comment by KrohmKoala** [comment] 2015-11-29 18:11
No problems :-)

**Comment by sekwah41** [comment] 2015-12-10 10:10
Please try this new test build :)

http://puu.sh/lOZSI/e067f6b9d7.jar

**Comment by sekwah41** [comment] 2015-12-10 10:10
Did not mean to close the issue....

**Comment by KrohmKoala** [comment] 2015-12-10 12:28
It seems to be resolved :D

**Comment by sekwah41** [comment] 2015-12-10 14:20
Great ^.^

**Closed** 2015-12-10 14:20 UTC
Labels: bug
