### ISSUE TITLE
Nether portal teleports to nether instead of destination. (video included)

### ISSUE THREAD

**Issue by Tomasan7** [sekwah41/Advanced-Portals#228] opened 2020-12-04 18:26 UTC
So I have AdvancedPortals portal on spawn. The portal is made of NETHER_PORTAL portal block and has set a destination. But when you walk into it, it blinks (not in vid, for some reason) with a correct destination, but 90% of time it teleports you to nether instead of the set destination. Also I have 

Here is **config.yml**:
```
UseOnlyServerMadeAxe: true
AxeItemId: IRON_AXE
CanBuildPortalBlock: true
PortalProtection: false
PortalProtectionArea: 5
DefaultPortalTriggerBlock: NETHER_PORTAL
StopWaterFlow: true
ShowSelectionBlockID: RED_STAINED_GLASS
WarpParticles: 0
WarpSound: 0
ShowBungeeWarpMessage: false
ShowSelectionShowDuration: 10
WarpMessageDisplay: 0
UseWarpPrefix: true
UseCustomPrefix: false
CustomPrefix: '&a[&eAdvancedPortals&a]'
CustomPrefixFail: '&c[&7AdvancedPortals&c]'
BlockSpectatorMode: false
PortalCooldown: 5
ThrowbackAmount: 0.7
DisableGatewayBeam: false
CommandLevels: opcb
ConfigVersion: true
```

Here is **portals.yml**:
```
...
Spawn-Creative:
  world: Spawn
  triggerblock: NETHER_PORTAL
  destination: Creative
  pos1:
    X: 14
    Y: 73
    Z: 11
  pos2:
    X: 10
    Y: 69
    Z: 11
...
```

Here is **destionations.yml**:
```
...
Creative:
  world: creative
  pos:
    X: 27.5
    Y: 61.0
    Z: -44.5
    pitch: 0
    yaw: 0
...
```

Here is evidence video: https://youtu.be/ORG7J6Xe5PM
(the other portal is without desti, but with command and works fine)

You can test it by yourself on **mc.survivalcraft.cz** just register and then use **/spawn** command, and you should be at the same place as in video.

EDIT: Now I figured out, that it works just fine in creative.

EDIT2: After a couple more research, this is what I found out:
![AdvancedPortalsDiagram](https://user-images.githubusercontent.com/47734291/101260471-7d97f280-3730-11eb-9d64-54ef952f1536.png)

**Comment by sekwah41** [comment] 2020-12-04 19:54
Creative mode has a weird thing where it instantly teleports. Are you using paper or normal spigot? I may need to alter some of the events.

**Comment by sekwah41** [comment] 2020-12-04 20:15
Seems to possibly be an issue with paper. Please test however I will try to replicate it and see if I can fix (I don't usually support paperspigot issues)

**Comment by pmosbach** [comment] 2021-06-22 19:26
Just ran into this issue on 1.17 spigot so it may not be particular to paper

**Comment by Tomasan7** [comment] 2021-06-22 19:36
It does it on spigot as well, I tested it before.

**Comment by sekwah41** [comment] 2021-06-23 23:32
I will look into this when I can, annoyingly it doesnt seem always the easiest to re-create

**Comment by sekwah41** [comment] 2021-07-02 01:48
Seems to be more widespread on 1.17 so I will spend some time this weekend re-creating it ^.^

**Comment by sekwah41** [comment] 2021-07-05 01:37
https://medal.tv/clips/3QfNJIPhr3ZbK/d1337zJ4AYIc another clip of this happening

**Comment by sekwah41** [comment] 2021-07-05 02:06
Using the exact diagram provided by @Tomasan7 i have been able to reproduce this in the latest 1.17 branch of paper exactly as described

**Comment by sekwah41** [comment] 2021-07-05 02:13
https://user-images.githubusercontent.com/3209834/124408789-e71bc600-dd3e-11eb-83d9-ac10618e4358.mp4

Just for evidence that the testing setup re-creates the issue

**Comment by sekwah41** [comment] 2021-07-06 22:38
Should now be fixed in the next release
Uploading 2021-07-06 23-36-31_Trim.mp4…

**Comment by sekwah41** [comment] 2021-07-06 22:47
Once its confirmed if its working for the other users I will release the new version.

**Closed** 2021-07-14 08:34 UTC
Labels: bug
